# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: Apache-2.0
#

# Ensure that the SPI NOR driver is disabled by default
CONFIG_SPI_NOR=n

CONFIG_NCS_MCUBOOT_DISABLE_SELF_RWX=y

CONFIG_BOOT_WATCHDOG_FEED=n
