/*
 *  Copyright (c) 2026 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#ifndef __MCUBOOT_UUID_GENERATED_H__
#define __MCUBOOT_UUID_GENERATED_H__

/**
 * @file mcuboot_uuid_generated.h
 *
 * @note APIs declared in this file are generated by the gen_mcuboot_config.py script and should
 *       be aligned with templates.
 */

#include <bootutil/mcuboot_uuid.h>

#ifdef __cplusplus
extern "C" {
#endif

/** The automatically generated UUID map entry structure. */
struct uuid_map_entry {
	const struct device *dev;
	size_t off;
	size_t size;
	size_t image_index;
	size_t partition_index;
	struct image_uuid uuid;
};

/**
 * @brief Get the map of vendor UUIDs.
 *
 * @return The number of entries in the vendor UUID map, or 0 if the map is not available.
 */
size_t boot_uuid_vid_map_get(const struct uuid_map_entry **map);

/**
 * @brief Get the map of class UUIDs.
 *
 * @return The number of entries in the class UUID map, or 0 if the map is not available.
 */
size_t boot_uuid_cid_map_get(const struct uuid_map_entry **map);

#ifdef __cplusplus
}
#endif

#endif /* __MCUBOOT_UUID_GENERATED_H__ */
